name: Makefile CI

on:
  push:
    branches: [ "s9863a1h10_Natv-user-9-PPR1.180610.011-307-release-keys" ]
  pull_request:
    branches: [ "s9863a1h10_Natv-user-9-PPR1.180610.011-307-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
